### ISSUE TITLE
Error when installing tollbox

### ISSUE THREAD

**Issue by laurazh** [Quantiacs/quantiacs-python#9]
I try to pip install the toolbax with `pip install -U quantiacsToolbox`

but get the following error  `Command "python setup.py egg_info" failed with error code `

I try with different pip version but with no change.

I am using python 2.7

**Comment by MarkoCen** [comment]
Same here,

OS: Windows 10
Python: 2.7.15

```
$ pip install -U quantiacsToolbox
Collecting quantiacsToolbox
  Using cached https://files.pythonhosted.org/packages/7f/15/84d4dc8229cb6394b8bd06d1de6a10e25f819e56af2e624efe9a5a660fe0/quantiacsToolbox-3.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\xcen\appdata\local\temp\pip-install-olm27e\quantiacsToolbox\setup.py", line 3, in <module>
        from quantiacsToolbox.version import __version__
      File "quantiacsToolbox\__init__.py", line 3, in <module>
        from .quantiacsToolbox import runts, optimize, loadData, plotts, stats, submit, computeFees, updateCheck
      File "quantiacsToolbox\quantiacsToolbox.py", line 5, in <module>
        import requests
    ImportError: No module named requests

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\xcen\appdata\local\temp\pip-install-olm27e\quantiacsToolbox\
```
